### ISSUE TITLE
Python 3.5.1 not so fixed

### ISSUE THREAD

**Issue by LourensVeen** [yatiml/yatiml#19]
YAtiML 0.5.0 was supposed to work with Python 3.5.1, but apparently it doesn't:
```
type_ = typing.Dict[str, typing.Union[str, int, float, typing.List[float], typing.List[typing.List[float]], yatiml.util.bool_union_fix]]

    def generic_type_args(type_: Type) -> List[Type]:
        """Gets the type argument list for the given generic type.
    
        If you give this function List[int], it will return [int], and
        if you give it Union[int, str] it will give you [int, str]. Note
        that on Python < 3.7, Union[int, bool] collapses to Union[int] and
        then to int; this is already done by the time this function is
        called, so it does not help with that.
    
        Args:
            type_: The type to get the arguments list of.
    
        Returns:
            A list of Type objects.
        """
        if hasattr(type_, '__union_params__'):
            # 3.5 Union
            return list(type_.__union_params__)
>       return list(type_.__args__)
E       AttributeError: type object 'Dict' has no attribute '__args__'

.eggs/yatiml-0.5.0-py3.5.egg/yatiml/util.py:123: AttributeError
```
- [x] Set up Python 3.5.1 CI
- [x] Fix issue, use `List.__parameters__` if `__args__` does not exist.
